### PR TITLE
WIP: Feature/v2

### PR DESCRIPTION
**Pull request by Murr42**

### CODE REVIEW

**Comment by disturb01** [comment]
The current way of log the execution time, is to get the *elapased* time from the `startTime` field. This approach will be broken with a global logger.
Maybe we could replace the `startTime` at the start of each goroutine, however I'm not sure if that will work.

**Comment by Murr42** [comment]
@disturb01 I've already done that. Execution time is evaluated based on context's `startTime`

**Comment by disturb01** [comment]
I don't think is a good idea to manipulate the context of a global instance of the logger, is very unlikely but we could face the issue when to `goroutines` try to access and modify the context. That could cause some errors or false "execution time" values.

**Comment by Murr42** [comment]
Context is not global in the logger. There are no false "ms" values here. You can assure yourself that it's not the case running following code snippet:

```go
package main

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/sanservices/apilogger/v2"
)

func main() {
	ctx := context.TODO()

	ctx = context.WithValue(ctx, apilogger.APIKEY, "apikey1")
	ctx = context.WithValue(ctx, apilogger.RequestIDKey, "requestIdKey1")
	ctx = context.WithValue(ctx, apilogger.RemoteAddrKey, "remoteaddrKey1")
	ctx = context.WithValue(ctx, apilogger.SessionIDKey, "sessionIdKey1")

	startTime := time.Now()
	ctx = context.WithValue(ctx, apilogger.StartTime, startTime)

	apilogger.New(ctx, "")

	var wg sync.WaitGroup
	var mu sync.Mutex

	wg.Add(3)
	go func() {
		mu.Lock()
		fmt.Println("Time passed", time.Since(startTime))
		apilogger.Info(ctx, apilogger.LogCatDebug, "This is an info message gr I")
		mu.Unlock()

		time.Sleep(time.Millisecond * 100)

		mu.Lock()
		fmt.Println("Time passed", time.Since(startTime))
		apilogger.Warn(ctx, apilogger.LogCatDebug, "This is a warning message gr I")
		mu.Unlock()

		time.Sleep(time.Millisecond * 100)

		mu.Lock()
		fmt.Println("Time passed", time.Since(startTime))
		apilogger.Error(ctx, apilogger.LogCatDebug, "This is an error message gr I")
		mu.Unlock()

		wg.Done()
	}()

	go func() {
		mu.Lock()
		fmt.Println("Time passed", time.Since(startTime))
		apilogger.Info(ctx, apilogger.LogCatDebug, "This is an info message gr II")
		mu.Unlock()

		time.Sleep(time.Millisecond * 100)

		mu.Lock()
		fmt.Println("Time passed", time.Since(startTime))
		apilogger.Warn(ctx, apilogger.LogCatDebug, "This is a warning message gr II")
		mu.Unlock()

		mu.Lock()
		fmt.Println("Time passed", time.Since(startTime))
		apilogger.Error(ctx, apilogger.LogCatDebug, "This is an error message gr II")
		mu.Unlock()

		wg.Done()
	}()

	go func() {
		mu.Lock()
		fmt.Println("Time passed", time.Since(startTime))
		apilogger.Info(ctx, apilogger.LogCatDebug, "This is an info message gr III")
		mu.Unlock()

		time.Sleep(time.Millisecond * 100)

		mu.Lock()
		fmt.Println("Time passed", time.Since(startTime))
		apilogger.Warn(ctx, apilogger.LogCatDebug, "This is a warning message gr III")
		mu.Unlock()

		mu.Lock()
		fmt.Println("Time passed", time.Since(startTime))
		apilogger.Error(ctx, apilogger.LogCatDebug, "This is an error message gr III")
		mu.Unlock()

		wg.Done()
	}()

	wg.Wait()
}
```

**Comment by Murr42** [comment]
I used mutex to isolate pair of apilogger and print calls not to create mess in output

**Comment by Murr42** [comment]
Context is not modified in case it is kinda transactional, so it is perfectly okay to use context on every local or global logger call

**Comment by disturb01** [comment]
Ok, I see now that you are passing the context for each method. Great.

**Pull request merged**
